apiVersion: v1
kind: Deployment
metadata:
  name: steganography-app
  namespace: steganography-ns
spec:
  replcias: 1
  selector:
    matchLabels:
      app: steganography
  template:
    metadata:
      labels:
        app: steganography
    spec:
      containers:
      - name: steganography
        image: christopher402/steganography:1.0.0
        ports:
        - name: web
          cotainerPort: 8080