apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: steganography-ingress
  namespace: steganography-ns
spec:
  ingressClassName: traefik
  rules:
  - host: "steganography.tira.com.ro"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: steganography-svc
            port:
              number: 8080